In [1]:
import pandas as pd

bls_path = "../data/datasets/bls_occupation.xlsx"

bls_file = pd.ExcelFile(bls_path)

bls_file.sheet_names

['Index',
 'Table 1.1',
 'Table 1.2',
 'Table 1.3',
 'Table 1.4',
 'Table 1.5',
 'Table 1.6',
 'Table 1.8',
 'Table 1.9',
 'Table 1.10',
 'Table 1.11',
 'Table 1.12']

In [2]:
bls_raw = pd.read_excel(
    bls_path,
    sheet_name="Table 1.2",
    header=None
)

bls_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,"Table 1.2 Occupational projections, 2025–35, a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment distribution, percent, 2025","Employment distribution, percent, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35 annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain c...,Related Occupational Outlook Handbook (OOH) co...,Related Occupational Outlook Handbook (OOH) co...
2,"Total, all occupations",00-0000,Summary,170280.8,176198.5,100,100,5917.6,3.5,5.8,17461.8,50980,—,—,—,—,—
3,Management occupations,11-0000,Summary,13683.4,14527.6,8,8.2,844.2,6.2,14.4,1081.7,126520,—,—,—,—,—
4,Top executives,11-1000,Summary,3904.1,4095.2,2.3,2.3,191.1,4.9,2.7,305.1,108510,—,—,—,—,—
5,Chief executives,11-1011,Line item,291.6,300.9,0.2,0.2,9.3,3.2,26.6,19.1,213990,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/to..."
6,General and operations managers,11-1021,Line item,3599,3780.3,2.1,2.1,181.3,5,0.8,285,105770,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/to..."
7,"Advertising, marketing, promotions, public...",11-2000,Summary,1234.5,1298.6,0.7,0.7,64.1,5.2,3.2,93.4,155780,—,—,—,—,—
8,Advertising and promotions managers,11-2011,Line item,33.2,31.9,0,0,-1.2,-3.7,35.1,2.3,133660,Bachelor's degree,Less than 5 years,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/ad..."
9,Marketing and sales managers,11-2020,Summary,1071.7,1129.9,0.6,0.6,58.1,5.4,2.6,81.2,158040,—,—,—,—,—
10,Marketing managers,11-2021,Line item,421.6,450.8,0.2,0.3,29.1,6.9,5.3,34,166790,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/ad..."
11,Sales managers,11-2022,Line item,650.1,679.1,0.4,0.4,29,4.5,0.8,47.3,148270,Bachelor's degree,Less than 5 years,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/sa..."
12,Public relations and fundraising managers,11-2030,Summary,129.6,136.8,0.1,0.1,7.2,5.6,0.4,9.8,136470,—,—,—,—,—
13,Public relations managers,11-2032,Line item,80.8,85.4,0,0,4.6,5.7,0.4,6.1,146910,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/pu..."
14,Fundraising managers,11-2033,Line item,48.8,51.4,0,0,2.6,5.4,0.3,3.7,125470,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/pu..."

In [4]:
bls = pd.read_excel(
    bls_path,
    sheet_name="Table 1.2",
    header=1
)

bls.head()

,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment distribution, percent, 2025","Employment distribution, percent, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35 annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content,Related Occupational Outlook Handbook (OOH) content.1
0,"Total, all occupations",00-0000,Summary,170280.8,176198.5,100.0,100.0,5917.6,3.5,5.8,17461.8,50980,—,—,—,—,—
1,Management occupations,11-0000,Summary,13683.4,14527.6,8.0,8.2,844.2,6.2,14.4,1081.7,126520,—,—,—,—,—
2,Top executives,11-1000,Summary,3904.1,4095.2,2.3,2.3,191.1,4.9,2.7,305.1,108510,—,—,—,—,—
3,Chief executives,11-1011,Line item,291.6,300.9,0.2,0.2,9.3,3.2,26.6,19.1,213990,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/to..."
4,General and operations managers,11-1021,Line item,3599.0,3780.3,2.1,2.1,181.3,5.0,0.8,285.0,105770,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/to..."

In [6]:
bls.shape

(1117, 17)

In [7]:
bls.columns.tolist()

['2025 National Employment Matrix title',
 '2025 National Employment Matrix code',
 'Occupation type',
 'Employment, 2025',
 'Employment, 2035',
 'Employment distribution, percent, 2025',
 'Employment distribution, percent, 2035',
 'Employment change, numeric, 2025–35',
 'Employment change, percent, 2025–35',
 'Percent self-employed, 2025',
 'Occupational openings, 2025–35 annual average',
 'Median annual wage, dollars, 2025',
 'Typical education needed for entry',
 'Work experience in a related occupation',
 'Typical on-the-job training needed to attain competency in the occupation',
 'Related Occupational Outlook Handbook (OOH) content',
 'Related Occupational Outlook Handbook (OOH) content.1']

In [9]:
bls["Occupation type"].value_counts(dropna=False)

Occupation type
Line item    831
Summary      281
NaN            5
Name: count, dtype: int64

In [11]:
bls[bls["Occupation type"].isna()]

,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment distribution, percent, 2025","Employment distribution, percent, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35 annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content,Related Occupational Outlook Handbook (OOH) content.1
1112,Note:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,Wage data are from the Occupational Employment...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,Data is unavailable for values denoted with a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,Employment subcategories do not necessarily ad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Source: U.S. Bureau of Labor Statistics.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
bls.loc[
    bls["Occupation type"].isna(),
    [
        "2025 National Employment Matrix title",
        "2025 National Employment Matrix code"
    ]
]

,2025 National Employment Matrix title,2025 National Employment Matrix code
1112,Note:,NaN
1113,Wage data are from the Occupational Employment...,NaN
1114,Data is unavailable for values denoted with a ...,NaN
1115,Employment subcategories do not necessarily ad...,NaN
1116,Source: U.S. Bureau of Labor Statistics.,NaN

In [15]:
bls_line = bls[
    bls["Occupation type"] == "Line item"
].copy()

bls_line.shape

(831, 17)

In [17]:
bls_line[
    [
        "2025 National Employment Matrix title",
        "2025 National Employment Matrix code",
        "Employment change, percent, 2025–35"
    ]
].head()

,2025 National Employment Matrix title,2025 National Employment Matrix code,"Employment change, percent, 2025–35"
3,Chief executives,11-1011,3.2
4,General and operations managers,11-1021,5.0
6,Advertising and promotions managers,11-2011,-3.7
8,Marketing managers,11-2021,6.9
9,Sales managers,11-2022,4.5

In [19]:
bls_line["Employment change, percent, 2025–35"].value_counts(dropna=False).head(10)

Employment change, percent, 2025–35
 2.6    14
 4.0    14
-0.3    14
 3.7    13
 2.0    13
 5.5    12
 2.4    12
 2.7    12
 5.8    11
 3.8    11
Name: count, dtype: int64

In [21]:
bls_line["Employment change, percent, 2025–35"].dtype

dtype('float64')

In [23]:
bls_line["Employment change, percent, 2025–35"].isna().sum()

np.int64(0)

In [25]:
(bls_line["Employment change, percent, 2025–35"] == "—").sum()

np.int64(0)

In [27]:
bls_line["2025 National Employment Matrix code"].head(10)

3     11-1011
4     11-1021
6     11-2011
8     11-2021
9     11-2022
11    11-2032
12    11-2033
15    11-3012
16    11-3013
17    11-3021
Name: 2025 National Employment Matrix code, dtype: str

In [29]:
bls_line["2025 National Employment Matrix code"].nunique()

831

In [31]:
bls_line["2025 National Employment Matrix code"].str.match(
    r"^\d{2}-\d{4}$"
).value_counts()

2025 National Employment Matrix code
True    831
Name: count, dtype: int64

In [33]:
merged_v0 = pd.read_csv(
    "../data/datasets/processed/merged_v0.csv",
    dtype={"soc2018": "string"}
)

merged_v0.shape

(798, 214)

In [35]:
merged_v0["soc2018"].head(10)

0    11-1011
1    11-1021
2    11-1031
3    11-2011
4    11-2021
5    11-2022
6    11-2032
7    11-2033
8    11-3012
9    11-3013
Name: soc2018, dtype: string

In [37]:
merged_v0["soc2018"].nunique()

798

In [39]:
merged_v0["soc2018"].str.match(
    r"^\d{2}-\d{4}$"
).value_counts(dropna=False)

soc2018
True    798
Name: count, dtype: Int64

In [41]:
bls_line["soc2018"] = (
    bls_line["2025 National Employment Matrix code"]
    .astype("string")
    .str.strip()
)

In [43]:
bls_match = merged_v0["soc2018"].isin(bls_line["soc2018"])

bls_match.value_counts()

soc2018
True     772
False     26
Name: count, dtype: int64

In [45]:
bls_match.mean()

np.float64(0.9674185463659147)

In [47]:
merged_v0.loc[
    ~bls_match,
    ["soc2018", "title"]
]

     soc2018                                              title
2    11-1031                                        Legislators
38   13-1021        Buyers and Purchasing Agents, Farm Products
39   13-1022  Wholesale and Retail Buyers, Except Farm Products
40   13-1023  Purchasing Agents, Except Wholesale, Retail, a...
58   13-2022       Appraisers of Personal and Business Property
59   13-2023            Appraisers and Assessors of Real Estate
175  21-1011  Substance Abuse and Behavioral Disorder Counse...
178  21-1014                           Mental Health Counselors
239  25-2055           Special Education Teachers, Kindergarten
240  25-2056      Special Education Teachers, Elementary School
255  25-9042  Teaching Assistants, Preschool, Elementary, Mi...
256  25-9043             Teaching Assistants, Special Education
337  29-2011      Medical and Clinical Laboratory Technologists
338  29-2012        Medical and Clinical Laboratory Technicians
364  31-1121                                  Home Health Aides
365  31-1122                                Personal Care Aides
452  39-7011                            Tour Guides and Escorts
453  39-7012                                      Travel Guides
585  47-4091                                   Segmental Pavers
586  47-4099        Construction and Related Workers, All Other
652  51-2022     Electrical and Electronic Equipment Assemblers
653  51-2023             Electromechanical Equipment Assemblers
658  51-2092                                    Team Assemblers
751  53-1042  First-Line Supervisors of Helpers, Laborers, a...
752  53-1043  First-Line Supervisors of Material-Moving Mach...
753  53-1044     First-line Supervisors of Passenger Attendants

In [49]:
merged_v0.columns.tolist()

['soc2018',
 'title',
 'eloundou_title',
 'onet_title',
 'dv_rating_alpha',
 'dv_rating_beta',
 'dv_rating_gamma',
 'human_rating_alpha',
 'human_rating_beta',
 'human_rating_gamma',
 'aioe',
 'aioe_source_rows',
 'aioe_source_codes',
 'aioe_crosswalk_changed',
 'fo_prob',
 'fo_source_rows',
 'fo_source_codes',
 'fo_crosswalk_changed',
 'onet_title_rollup_method',
 'job_zone',
 'job_zone_rollup_method',
 'job_zone_had_conflict',
 'job_zone_source_value_count',
 'ability_arm_hand_steadiness__1_a_2_a_1',
 'ability_auditory_attention__1_a_4_b_2',
 'ability_category_flexibility__1_a_1_b_7',
 'ability_control_precision__1_a_2_b_1',
 'ability_deductive_reasoning__1_a_1_b_4',
 'ability_depth_perception__1_a_4_a_6',
 'ability_dynamic_flexibility__1_a_3_c_2',
 'ability_dynamic_strength__1_a_3_a_3',
 'ability_explosive_strength__1_a_3_a_2',
 'ability_extent_flexibility__1_a_3_c_1',
 'ability_far_vision__1_a_4_a_2',
 'ability_finger_dexterity__1_a_2_a_3',
 'ability_flexibility_of_closure__1_a_1_e_2',
 'ability_fluency_of_ideas__1_a_1_b_1',
 'ability_glare_sensitivity__1_a_4_a_7',
 'ability_gross_body_coordination__1_a_3_c_3',
 'ability_gross_body_equilibrium__1_a_3_c_4',
 'ability_hearing_sensitivity__1_a_4_b_1',
 'ability_inductive_reasoning__1_a_1_b_5',
 'ability_information_ordering__1_a_1_b_6',
 'ability_manual_dexterity__1_a_2_a_2',
 'ability_mathematical_reasoning__1_a_1_c_1',
 'ability_memorization__1_a_1_d_1',
 'ability_multilimb_coordination__1_a_2_b_2',
 'ability_near_vision__1_a_4_a_1',
 'ability_night_vision__1_a_4_a_4',
 'ability_number_facility__1_a_1_c_2',
 'ability_oral_comprehension__1_a_1_a_1',
 'ability_oral_expression__1_a_1_a_3',
 'ability_originality__1_a_1_b_2',
 'ability_perceptual_speed__1_a_1_e_3',
 'ability_peripheral_vision__1_a_4_a_5',
 'ability_problem_sensitivity__1_a_1_b_3',
 'ability_rate_control__1_a_2_b_4',
 'ability_reaction_time__1_a_2_c_1',
 'ability_response_orientation__1_a_2_b_3',
 'ability_selective_attention__1_a_1_g_1',
 'ability_sound_localization__1_a_4_b_3',
 'ability_spatial_orientation__1_a_1_f_1',
 'ability_speech_clarity__1_a_4_b_5',
 'ability_speech_recognition__1_a_4_b_4',
 'ability_speed_of_closure__1_a_1_e_1',
 'ability_speed_of_limb_movement__1_a_2_c_3',
 'ability_stamina__1_a_3_b_1',
 'ability_static_strength__1_a_3_a_1',
 'ability_time_sharing__1_a_1_g_2',
 'ability_trunk_strength__1_a_3_a_4',
 'ability_visual_color_discrimination__1_a_4_a_3',
 'ability_visualization__1_a_1_f_2',
 'ability_wrist_finger_speed__1_a_2_c_2',
 'ability_written_comprehension__1_a_1_a_2',
 'ability_written_expression__1_a_1_a_4',
 'skill_active_learning__2_a_2_b',
 'skill_active_listening__2_a_1_b',
 'skill_complex_problem_solving__2_b_2_i',
 'skill_coordination__2_b_1_b',
 'skill_critical_thinking__2_a_2_a',
 'skill_equipment_maintenance__2_b_3_j',
 'skill_equipment_selection__2_b_3_c',
 'skill_installation__2_b_3_d',
 'skill_instructing__2_b_1_e',
 'skill_judgment_and_decision_making__2_b_4_e',
 'skill_learning_strategies__2_a_2_c',
 'skill_management_of_financial_resources__2_b_5_b',
 'skill_management_of_material_resources__2_b_5_c',
 'skill_management_of_personnel_resources__2_b_5_d',
 'skill_mathematics__2_a_1_e',
 'skill_monitoring__2_a_2_d',
 'skill_negotiation__2_b_1_d',
 'skill_operation_and_control__2_b_3_h',
 'skill_operations_analysis__2_b_3_a',
 'skill_operations_monitoring__2_b_3_g',
 'skill_persuasion__2_b_1_c',
 'skill_programming__2_b_3_e',
 'skill_quality_control_analysis__2_b_3_m',
 'skill_reading_comprehension__2_a_1_a',
 'skill_repairing__2_b_3_l',
 'skill_science__2_a_1_f',
 'skill_service_orientation__2_b_1_f',
 'skill_social_perceptiveness__2_b_1_a',
 'skill_speaking__2_a_1_d',
 'skill_systems_analysis__2_b_4_g',
 'skill_systems_evaluation__2_b_4_h',
 'skill_technology_design__2_b_3_b',
 'skill_time_management__2_b_5_a',
 'skill_troubleshooting__2_b_3_k',
 'skill_writing__2_a_1_c',
 'work_activity_analyzing_data_or_information__4_a_2_a_4',
 'work_activity_assisting_and_caring_for_others__4_a_4_a_5',
 'work_activity_coaching_and_developing_others__4_a_4_b_5',
 'work_activity_communicating_with_people_outside_the_organization__4_a_4_a_3',
 'work_activity_communicating_with_supervisors_peers_or_subordinates__4_a_4_a_2',
 'work_activity_controlling_machines_and_processes__4_a_3_a_3',
 'work_activity_coordinating_the_work_and_activities_of_others__4_a_4_b_1',
 'work_activity_developing_and_building_teams__4_a_4_b_2',
 'work_activity_developing_objectives_and_strategies__4_a_2_b_4',
 'work_activity_documenting_recording_information__4_a_3_b_6',
 'work_activity_drafting_laying_out_and_specifying_technical_devices_parts_and_equipment__4_a_3_b_2',
 'work_activity_establishing_and_maintaining_interpersonal_relationships__4_a_4_a_4',
 'work_activity_estimating_the_quantifiable_characteristics_of_products_events_or_information__4_a_1_b_3',
 'work_activity_evaluating_information_to_determine_compliance_with_standards__4_a_2_a_3',
 'work_activity_getting_information__4_a_1_a_1',
 'work_activity_guiding_directing_and_motivating_subordinates__4_a_4_b_4',
 'work_activity_handling_and_moving_objects__4_a_3_a_2',
 'work_activity_identifying_objects_actions_and_events__4_a_1_b_1',
 'work_activity_inspecting_equipment_structures_or_materials__4_a_1_b_2',
 'work_activity_interpreting_the_meaning_of_information_for_others__4_a_4_a_1',
 'work_activity_judging_the_qualities_of_objects_services_or_people__4_a_2_a_1',
 'work_activity_making_decisions_and_solving_problems__4_a_2_b_1',
 'work_activity_monitoring_and_controlling_resources__4_a_4_c_3',
 'work_activity_monitoring_processes_materials_or_surroundings__4_a_1_a_2',
 'work_activity_operating_vehicles_mechanized_devices_or_equipment__4_a_3_a_4',
 'work_activity_organizing_planning_and_prioritizing_work__4_a_2_b_6',
 'work_activity_performing_administrative_activities__4_a_4_c_1',
 'work_activity_performing_for_or_working_directly_with_the_public__4_a_4_a_8',
 'work_activity_performing_general_physical_activities__4_a_3_a_1',
 'work_activity_processing_information__4_a_2_a_2',
 'work_activity_providing_consultation_and_advice_to_others__4_a_4_b_6',
 'work_activity_repairing_and_maintaining_electronic_equipment__4_a_3_b_5',
 'work_activity_repairing_and_maintaining_mechanical_equipment__4_a_3_b_4',
 'work_activity_resolving_conflicts_and_negotiating_with_others__4_a_4_a_7',
 'work_activity_scheduling_work_and_activities__4_a_2_b_5',
 'work_activity_selling_or_influencing_others__4_a_4_a_6',
 'work_activity_staffing_organizational_units__4_a_4_c_2',
 'work_activity_thinking_creatively__4_a_2_b_2',
 'work_activity_training_and_teaching_others__4_a_4_b_3',
 'work_activity_updating_and_using_relevant_knowledge__4_a_2_b_3',
 'work_activity_working_with_computers__4_a_3_b_1',
 'work_context_conflict_situations__4_c_1_d_1',
 'work_context_consequence_of_error__4_c_3_a_1',
 'work_context_contact_with_others__4_c_1_a_4',
 'work_context_coordinate_or_lead_others_in_accomplishing_work_activities__4_c_1_b_1_g',
 'work_context_deal_with_external_customers_or_the_public_in_general__4_c_1_b_1_f',
 'work_context_dealing_with_unpleasant_angry_or_discourteous_people__4_c_1_d_2',
 'work_context_dealing_with_violent_or_physically_aggressive_people__4_c_1_d_3',
 'work_context_degree_of_automation__4_c_3_b_2',
 'work_context_determine_tasks_priorities_and_goals__4_c_3_b_8',
 'work_context_e_mail__4_c_1_a_2_h',
 'work_context_exposed_to_contaminants__4_c_2_b_1_d',
 'work_context_exposed_to_cramped_work_space_awkward_positions__4_c_2_b_1_e',
 'work_context_exposed_to_disease_or_infections__4_c_2_c_1_b',
 'work_context_exposed_to_extremely_bright_or_inadequate_lighting_conditions__4_c_2_b_1_c',
 'work_context_exposed_to_hazardous_conditions__4_c_2_c_1_d',
 'work_context_exposed_to_hazardous_equipment__4_c_2_c_1_e',
 'work_context_exposed_to_high_places__4_c_2_c_1_c',
 'work_context_exposed_to_minor_burns_cuts_bites_or_stings__4_c_2_c_1_f',
 'work_context_exposed_to_radiation__4_c_2_c_1_a',
 'work_context_exposed_to_sounds_noise_levels_that_are_distracting_or_uncomfortable__4_c_2_b_1_a',
 'work_context_exposed_to_very_hot_or_cold_temperatures__4_c_2_b_1_b',
 'work_context_exposed_to_whole_body_vibration__4_c_2_b_1_f',
 'work_context_face_to_face_discussions_with_individuals_and_within_teams__4_c_1_a_2_l',
 'work_context_freedom_to_make_decisions__4_c_3_a_4',
 'work_context_frequency_of_decision_making__4_c_3_a_2_b',
 'work_context_health_and_safety_of_other_workers__4_c_1_c_1',
 'work_context_impact_of_decisions_on_co_workers_or_company_results__4_c_3_a_2_a',
 'work_context_importance_of_being_exact_or_accurate__4_c_3_b_4',
 'work_context_importance_of_repeating_same_tasks__4_c_3_b_7',
 'work_context_in_an_enclosed_vehicle_or_operate_enclosed_equipment__4_c_2_a_1_f',
 'work_context_in_an_open_vehicle_or_operating_equipment__4_c_2_a_1_e',
 'work_context_indoors_environmentally_controlled__4_c_2_a_1_a',
 'work_context_indoors_not_environmentally_controlled__4_c_2_a_1_b',
 'work_context_level_of_competition__4_c_3_c_1',
 'work_context_outdoors_exposed_to_all_weather_conditions__4_c_2_a_1_c',
 'work_context_outdoors_under_cover__4_c_2_a_1_d',
 'work_context_pace_determined_by_speed_of_equipment__4_c_3_d_3',
 'work_context_physical_proximity__4_c_2_a_3',
 'work_context_public_speaking__4_c_1_a_2_c',
 'work_context_spend_time_bending_or_twisting_your_body__4_c_2_d_1_h',
 'work_context_spend_time_climbing_ladders_scaffolds_or_poles__4_c_2_d_1_c',
 'work_context_spend_time_keeping_or_regaining_balance__4_c_2_d_1_f',
 'work_context_spend_time_kneeling_crouching_stooping_or_crawling__4_c_2_d_1_e',
 'work_context_spend_time_making_repetitive_motions__4_c_2_d_1_i',
 'work_context_spend_time_sitting__4_c_2_d_1_a',
 'work_context_spend_time_standing__4_c_2_d_1_b',
 'work_context_spend_time_using_your_hands_to_handle_control_or_feel_objects_tools_or_controls__4_c_2_d_1_g',
 'work_context_spend_time_walking_or_running__4_c_2_d_1_d',
 'work_context_telephone_conversations__4_c_1_a_2_f',
 'work_context_time_pressure__4_c_3_d_1',
 'work_context_wear_common_protective_or_safety_equipment_such_as_safety_shoes_glasses_gloves_hearing_protection_hard_hats_or_life_jackets__4_c_2_e_1_d',
 'work_context_wear_specialized_protective_or_safety_equipment_such_as_breathing_apparatus_safety_harness_full_protection_suits_or_radiation_protection__4_c_2_e_1_e',
 'work_context_work_outcomes_and_results_of_other_workers__4_c_1_c_2',
 'work_context_work_with_or_contribute_to_a_work_group_or_team__4_c_1_b_1_e',
 'work_context_written_letters_and_memos__4_c_1_a_2_j',
 'in_eloundou',
 'in_aioe',
 'in_frey',
 'in_job_zones',
 'in_abilities',
 'in_skills',
 'in_work_activities',
 'in_work_context']

In [52]:
unmatched_bls = merged_v0.loc[
    ~bls_match,
    ["soc2018", "title"]
].copy()

unmatched_bls["appears_anywhere_in_bls"] = unmatched_bls["soc2018"].isin(
    bls["2025 National Employment Matrix code"]
)

unmatched_bls

,soc2018,title,appears_anywhere_in_bls
2,11-1031,Legislators,False
38,13-1021,"Buyers and Purchasing Agents, Farm Products",False
39,13-1022,"Wholesale and Retail Buyers, Except Farm Products",False
40,13-1023,"Purchasing Agents, Except Wholesale, Retail, a...",False
58,13-2022,Appraisers of Personal and Business Property,False
59,13-2023,Appraisers and Assessors of Real Estate,False
175,21-1011,Substance Abuse and Behavioral Disorder Counse...,False
178,21-1014,Mental Health Counselors,False
239,25-2055,"Special Education Teachers, Kindergarten",False
240,25-2056,"Special Education Teachers, Elementary School",False
255,25-9042,"Teaching Assistants, Preschool, Elementary, Mi...",False
256,25-9043,"Teaching Assistants, Special Education",False
337,29-2011,Medical and Clinical Laboratory Technologists,False
338,29-2012,Medical and Clinical Laboratory Technicians,False
364,31-1121,Home Health Aides,False
365,31-1122,Personal Care Aides,False
452,39-7011,Tour Guides and Escorts,False
453,39-7012,Travel Guides,False
585,47-4091,Segmental Pavers,False
586,47-4099,"Construction and Related Workers, All Other",False
652,51-2022,Electrical and Electronic Equipment Assemblers,False
653,51-2023,Electromechanical Equipment Assemblers,False
658,51-2092,Team Assemblers,False
751,53-1042,"First-Line Supervisors of Helpers, Laborers, a...",False
752,53-1043,First-Line Supervisors of Material-Moving Mach...,False
753,53-1044,First-line Supervisors of Passenger Attendants,False

In [56]:
unmatched_bls["appears_anywhere_in_bls"] = unmatched_bls["soc2018"].isin(
    bls["2025 National Employment Matrix code"]
)

unmatched_bls["appears_anywhere_in_bls"].value_counts()

appears_anywhere_in_bls
False    26
Name: count, dtype: int64

In [58]:
unmatched_bls

,soc2018,title,appears_anywhere_in_bls
2,11-1031,Legislators,False
38,13-1021,"Buyers and Purchasing Agents, Farm Products",False
39,13-1022,"Wholesale and Retail Buyers, Except Farm Products",False
40,13-1023,"Purchasing Agents, Except Wholesale, Retail, a...",False
58,13-2022,Appraisers of Personal and Business Property,False
59,13-2023,Appraisers and Assessors of Real Estate,False
175,21-1011,Substance Abuse and Behavioral Disorder Counse...,False
178,21-1014,Mental Health Counselors,False
239,25-2055,"Special Education Teachers, Kindergarten",False
240,25-2056,"Special Education Teachers, Elementary School",False
255,25-9042,"Teaching Assistants, Preschool, Elementary, Mi...",False
256,25-9043,"Teaching Assistants, Special Education",False
337,29-2011,Medical and Clinical Laboratory Technologists,False
338,29-2012,Medical and Clinical Laboratory Technicians,False
364,31-1121,Home Health Aides,False
365,31-1122,Personal Care Aides,False
452,39-7011,Tour Guides and Escorts,False
453,39-7012,Travel Guides,False
585,47-4091,Segmental Pavers,False
586,47-4099,"Construction and Related Workers, All Other",False
652,51-2022,Electrical and Electronic Equipment Assemblers,False
653,51-2023,Electromechanical Equipment Assemblers,False
658,51-2092,Team Assemblers,False
751,53-1042,"First-Line Supervisors of Helpers, Laborers, a...",False
752,53-1043,First-Line Supervisors of Material-Moving Mach...,False
753,53-1044,First-line Supervisors of Passenger Attendants,False

In [60]:
unmatched_bls["soc_family"] = unmatched_bls["soc2018"].str[:6]

bls_lookup = bls[
    [
        "2025 National Employment Matrix code",
        "2025 National Employment Matrix title",
        "Occupation type"
    ]
].copy()

bls_lookup["soc_family"] = (
    bls_lookup["2025 National Employment Matrix code"]
    .astype("string")
    .str[:6]
)

In [62]:
family_matches = unmatched_bls.merge(
    bls_lookup,
    on="soc_family",
    how="left"
)

family_matches[
    [
        "soc2018",
        "title",
        "2025 National Employment Matrix code",
        "2025 National Employment Matrix title",
        "Occupation type"
    ]
].sort_values("soc2018")

,soc2018,title,2025 National Employment Matrix code,2025 National Employment Matrix title,Occupation type
0,11-1031,Legislators,NaN,NaN,NaN
1,13-1021,"Buyers and Purchasing Agents, Farm Products",13-1020,Buyers and purchasing agents,Line item
2,13-1022,"Wholesale and Retail Buyers, Except Farm Products",13-1020,Buyers and purchasing agents,Line item
3,13-1023,"Purchasing Agents, Except Wholesale, Retail, a...",13-1020,Buyers and purchasing agents,Line item
4,13-2022,Appraisers of Personal and Business Property,13-2020,Property appraisers and assessors,Line item
5,13-2023,Appraisers and Assessors of Real Estate,13-2020,Property appraisers and assessors,Line item
6,21-1011,Substance Abuse and Behavioral Disorder Counse...,21-1010,Counselors,Summary
7,21-1011,Substance Abuse and Behavioral Disorder Counse...,21-1012,"Educational, guidance, and career coun...",Line item
8,21-1011,Substance Abuse and Behavioral Disorder Counse...,21-1013,Marriage and family therapists,Line item
9,21-1011,Substance Abuse and Behavioral Disorder Counse...,21-1015,Rehabilitation counselors,Line item
10,21-1011,Substance Abuse and Behavioral Disorder Counse...,21-1018,"Substance abuse, behavioral disorder, ...",Line item
11,21-1011,Substance Abuse and Behavioral Disorder Counse...,21-1019,"Counselors, all other",Line item
17,21-1014,Mental Health Counselors,21-1019,"Counselors, all other",Line item
16,21-1014,Mental Health Counselors,21-1018,"Substance abuse, behavioral disorder, ...",Line item
15,21-1014,Mental Health Counselors,21-1015,Rehabilitation counselors,Line item
12,21-1014,Mental Health Counselors,21-1010,Counselors,Summary
13,21-1014,Mental Health Counselors,21-1012,"Educational, guidance, and career coun...",Line item
14,21-1014,Mental Health Counselors,21-1013,Marriage and family therapists,Line item
18,25-2055,"Special Education Teachers, Kindergarten",25-2050,Special education teachers,Summary
19,25-2055,"Special Education Teachers, Kindergarten",25-2051,"Special education teachers, preschool",Line item
20,25-2055,"Special Education Teachers, Kindergarten",25-2052,"Special education teachers, kindergart...",Line item
21,25-2055,"Special Education Teachers, Kindergarten",25-2057,"Special education teachers, middle school",Line item
22,25-2055,"Special Education Teachers, Kindergarten",25-2058,"Special education teachers, secondary ...",Line item
23,25-2055,"Special Education Teachers, Kindergarten",25-2059,"Special education teachers, all other",Line item
29,25-2056,"Special Education Teachers, Elementary School",25-2059,"Special education teachers, all other",Line item
27,25-2056,"Special Education Teachers, Elementary School",25-2057,"Special education teachers, middle school",Line item
28,25-2056,"Special Education Teachers, Elementary School",25-2058,"Special education teachers, secondary ...",Line item
25,25-2056,"Special Education Teachers, Elementary School",25-2051,"Special education teachers, preschool",Line item
26,25-2056,"Special Education Teachers, Elementary School",25-2052,"Special education teachers, kindergart...",Line item
24,25-2056,"Special Education Teachers, Elementary School",25-2050,Special education teachers,Summary
30,25-9042,"Teaching Assistants, Preschool, Elementary, Mi...",25-9040,Teaching assistants,Summary
31,25-9042,"Teaching Assistants, Preschool, Elementary, Mi...",25-9044,"Teaching assistants, postsecondary",Line item
32,25-9042,"Teaching Assistants, Preschool, Elementary, Mi...",25-9045,"Teaching assistants, except postsecondary",Line item
33,25-9043,"Teaching Assistants, Special Education",25-9040,Teaching assistants,Summary
34,25-9043,"Teaching Assistants, Special Education",25-9044,"Teaching assistants, postsecondary",Line item
35,25-9043,"Teaching Assistants, Special Education",25-9045,"Teaching assistants, except postsecondary",Line item
36,29-2011,Medical and Clinical Laboratory Technologists,29-2010,Clinical laboratory technologists and te...,Line item
37,29-2012,Medical and Clinical Laboratory Technicians,29-2010,Clinical laboratory technologists and te...,Line item
38,31-1121,Home Health Aides,31-1120,Home health and personal care aides,Line item
39,31-1122,Personal Care Aides,31-1120,Home health and personal care aides,Line item
40,39-7011,Tour Guides and Escorts,39-7010,Tour and travel guides,Line item
41,39-7012,Travel Guides,39-7010,Tour and travel guides,Line item
42,47-4091,Segmental Pavers,47-4090,Miscellaneous construction and related w...,Line item
43,47-4099,"Construction and Related Workers, All Other",47-4090,Miscellaneous construction and related w...,Line item
44,51-2022,Electrical and Electronic Equipment Assemblers,51-2020,"Electrical, electronics, and electromech...",Summary
45,51-2022,Electrical and Electronic Equipment Assemblers,51-2021,"Coil winders, tapers, and finishers",Line item
46,51-2022,Electrical and Electronic Equipment Assemblers,51-2028,"Electrical, electronic, and electromec...",Line item
47,51-2023,Electromechanical Equipment Assemblers,51-2020,"Electrical, electronics, and electromech...",Summary
48,51-2023,Electromechanical Equipment Assemblers,51-2021,"Coil winders, tapers, and finishers",Line item
49,51-2023,Electromechanical Equipment Assemblers,51-2028,"Electrical, electronic, and electromec...",Line item
50,51-2092,Team Assemblers,51-2090,Miscellaneous assemblers and fabricators,Line item
51,53-1042,"First-Line Supervisors of Helpers, Laborers, a...",53-1041,Aircraft cargo handling supervisors,Line item
52,53-1042,"First-Line Supervisors of Helpers, Laborers, a...",53-1047,First-line supervisors of transportation...,Line item
53,53-1043,First-Line Supervisors of Material-Moving Mach...,53-1041,Aircraft cargo handling supervisors,Line item
54,53-1043,First-Line Supervisors of Material-Moving Mach...,53-1047,First-line supervisors of transportation...,Line item
55,53-1044,First-line Supervisors of Passenger Attendants,53-1041,Aircraft cargo handling supervisors,Line item
56,53-1044,First-line Supervisors of Passenger Attendants,53-1047,First-line supervisors of transportation...,Line item

In [64]:
bls_for_merge = bls_line[
    [
        "soc2018",
        "2025 National Employment Matrix title",
        "Employment, 2025",
        "Employment, 2035",
        "Employment change, numeric, 2025–35",
        "Employment change, percent, 2025–35",
        "Occupational openings, 2025–35 annual average"
    ]
].copy()

In [66]:
bls_for_merge = bls_for_merge.rename(
    columns={
        "2025 National Employment Matrix title": "bls_title",
        "Employment, 2025": "bls_emp_2025",
        "Employment, 2035": "bls_emp_2035",
        "Employment change, numeric, 2025–35": "bls_emp_change_numeric_2025_35",
        "Employment change, percent, 2025–35": "bls_emp_change_pct_2025_35",
        "Occupational openings, 2025–35 annual average": "bls_annual_openings_2025_35"
    }
)

bls_for_merge.head()

,soc2018,bls_title,bls_emp_2025,bls_emp_2035,bls_emp_change_numeric_2025_35,bls_emp_change_pct_2025_35,bls_annual_openings_2025_35
3,11-1011,Chief executives,291.6,300.9,9.3,3.2,19.1
4,11-1021,General and operations managers,3599.0,3780.3,181.3,5.0,285.0
6,11-2011,Advertising and promotions managers,33.2,31.9,-1.2,-3.7,2.3
8,11-2021,Marketing managers,421.6,450.8,29.1,6.9,34.0
9,11-2022,Sales managers,650.1,679.1,29.0,4.5,47.3

In [68]:
merged_with_bls = merged_v0.merge(
    bls_for_merge,
    on="soc2018",
    how="left",
    validate="one_to_one",
    indicator=True
)

merged_with_bls.shape

C:\Users\Staneisha\AppData\Local\Temp\ipykernel_26620\3178471493.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged_with_bls = merged_v0.merge(
C:\Users\Staneisha\AppData\Local\Temp\ipykernel_26620\3178471493.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged_with_bls = merged_v0.merge(

(798, 221)

In [70]:
merged_with_bls["_merge"].value_counts()

_merge
both          772
left_only      26
right_only      0
Name: count, dtype: int64

In [72]:
merged_with_bls["bls_emp_change_pct_2025_35"].isna().sum()

np.int64(26)

In [74]:
merged_with_bls["bls_exact_match"] = (
    merged_with_bls["_merge"] == "both"
)

In [80]:
"_merge" in merged_with_bls.columns

False

In [81]:
"bls_exact_match" in merged_with_bls.columns

True

In [83]:
merged_with_bls.to_csv(
    "../data/datasets/processed/merged_v0_bls.csv",
    index=False
)

In [85]:
unmatched_bls.to_csv(
    "../data/datasets/processed/bls_unmatched_soc.csv",
    index=False
)

In [87]:
bls_check = pd.read_csv(
    "../data/datasets/processed/merged_v0_bls.csv"
)

bls_check.shape

(798, 221)

In [89]:
bls_check["bls_exact_match"].value_counts()

bls_exact_match
True     772
False     26
Name: count, dtype: int64

## Task 7 Summary - Neisha

### BLS Employment Projections Table 1.2

The project BLS workbook contains Table 1.2 for the 2025–35 projection period.

### BLS data preparation
- Raw Table 1.2 rows: 1,117
- Line-item occupations: 831
- Summary rows: 281
- Footer/note rows: 5
- Unique line-item occupation codes: 831
- All 831 line-item codes follow the `##-####` occupation-code format.
- `Employment change, percent, 2025–35` was numeric with no missing or unavailable (`—`) values among the line-item occupations.

### Join to merged_v0
- `merged_v0` occupations: 798
- Exact BLS matches: 772
- Unmatched occupations: 26
- Exact match rate: 96.74%
- Rows after left join: 798

A left join was used so that every occupation already in `merged_v0` was preserved even when an exact BLS Employment Matrix code was unavailable.

### Unmatched occupations
The 26 unmatched SOC codes were absent from the complete BLS Table 1.2, not only from the filtered line-item data.

Investigation showed that many unmatched detailed occupations are represented in the BLS Employment Matrix by broader combined occupation codes. Examples include:

- `13-1021`, `13-1022`, and `13-1023` represented by BLS `13-1020`, Buyers and purchasing agents.
- `29-2011` and `29-2012` represented by BLS `29-2010`, Clinical laboratory technologists and technicians.
- `31-1121` and `31-1122` represented by BLS `31-1120`, Home health and personal care aides.
- `39-7011` and `39-7012` represented by BLS `39-7010`, Tour and travel guides.

The broader BLS projection was not automatically copied to the detailed occupations because that would require a methodological decision about assigning one aggregated projection to multiple SOC occupations.

### Outputs
- `data/datasets/processed/merged_v0_bls.csv`
- `data/datasets/processed/bls_unmatched_soc.csv`